plugins {
    id 'java'
}

group = 'com.populatedplayer'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "dmulloy2"
        url = "https://repo.dmulloy2.net/repository/public/"
    }
}

dependencies {
    // API limpa do Paper (Sem NMS)
    compileOnly 'io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT'
    
    // Dependência do ProtocolLib lendo o arquivo local
    compileOnly files('libs/ProtocolLib.jar')
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}