name: PopulatedPlayer
version: ${version}
main: com.populatedplayer.PopulatedPlayerPlugin
api-version: '1.20'
author: PopulatedPlayer
folia-supported: false
description: Simula jogadores online apenas no TAB e na contagem do servidor.
depend:
  - ProtocolLib
commands:
  manha:
    description: Define baixa quantidade de fake players online.
    usage: /manha
    permission: populatedplayer.control
  tarde:
    description: Define média quantidade de fake players online.
    usage: /tarde
    permission: populatedplayer.control
  noite:
    description: Define alta quantidade de fake players online.
    usage: /noite
    permission: populatedplayer.control
permissions:
  populatedplayer.control:
    description: Permite controlar os fake players por período.
    default: op
